### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by bantuist**
- Run tests with -- --coverage in travis.yml
- CurrentQuote snapshot
- QuoteSettings snapshot
- Timer snapshot
- Weather snapshot
- App

### CODE REVIEW

**Comment by psychometry** [comment]
why did you add default props?  doesn't that defeat the purpose of isRequired?

**Comment by bantuist** [comment]
Yes, your right @psychometry. They are redundant. I was just trying to get the snapshots to pass and didn't think about it. Do you think it's enough to just remove isRequired for the propTypes with defaultProps?

**Comment by bantuist** [comment]
I see, I thought about passing them in test but I wasn't sure the right way to do it. I will try to fix it.

**Comment by bantuist** [comment]
I'm going to push my Timer tests on a different branch.

**Pull request closed without merging**
